from enum import Enum


class StrEnum(str, Enum):
    """String-valued enum that serializes naturally in API and database payloads."""


class IdentityVerificationState(StrEnum):
    RESOLVED_EXACT = "RESOLVED_EXACT"
    RESOLVED_SAME_GEOMETRY_GROUP = "RESOLVED_SAME_GEOMETRY_GROUP"
    PARTIAL = "PARTIAL"
    UNRESOLVED = "UNRESOLVED"


class IdentityTimeBasis(StrEnum):
    MODEL_YEAR = "MODEL_YEAR"
    OEM_REVISION_LABEL = "OEM_REVISION_LABEL"
    EDITION_RELEASE = "EDITION_RELEASE"
    SALE_PERIOD = "SALE_PERIOD"
    MULTIPLE = "MULTIPLE"
    UNKNOWN = "UNKNOWN"


class EvidenceMethod(StrEnum):
    PUBLISHED = "PUBLISHED"
    MEASURED = "MEASURED"
    DERIVED = "DERIVED"
    ESTIMATED = "ESTIMATED"
    NONE = "NONE"


class ResolutionState(StrEnum):
    UNCONTESTED = "UNCONTESTED"
    CONFLICTING = "CONFLICTING"
    PREFERRED_WITH_CONFLICT = "PREFERRED_WITH_CONFLICT"
    SUPERSEDED = "SUPERSEDED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class VerificationState(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    REVIEWED = "REVIEWED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class AvailabilityState(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNKNOWN = "UNKNOWN"
    NOT_FOUND_AFTER_SEARCH = "NOT_FOUND_AFTER_SEARCH"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class DataType(StrEnum):
    NUMBER = "NUMBER"
    TEXT = "TEXT"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
    JSON = "JSON"


class AuthorityClass(StrEnum):
    REGULATORY_OFFICIAL = "REGULATORY_OFFICIAL"
    OEM_THAILAND = "OEM_THAILAND"
    OFFICIAL_LOCAL_DISTRIBUTOR_IMPORTER = "OFFICIAL_LOCAL_DISTRIBUTOR_IMPORTER"
    OEM_REGIONAL_GLOBAL = "OEM_REGIONAL_GLOBAL"
    OEM_SERVICE_TECHNICAL = "OEM_SERVICE_TECHNICAL"
    OEM_HOMOLOGATION_CERTIFICATION = "OEM_HOMOLOGATION_CERTIFICATION"
    REPUTABLE_SECONDARY = "REPUTABLE_SECONDARY"
    OTHER_SECONDARY = "OTHER_SECONDARY"
    PHYSICAL_MEASUREMENT = "PHYSICAL_MEASUREMENT"


class SourceType(StrEnum):
    WEB_SPECIFICATION = "WEB_SPECIFICATION"
    OWNER_MANUAL = "OWNER_MANUAL"
    SERVICE_MANUAL = "SERVICE_MANUAL"
    ENGINEERING_DRAWING = "ENGINEERING_DRAWING"
    HOMOLOGATION = "HOMOLOGATION"
    PHYSICAL_MEASUREMENT = "PHYSICAL_MEASUREMENT"
    DETERMINISTIC_FIXTURE = "DETERMINISTIC_FIXTURE"
    OTHER = "OTHER"


class ExtractionMethod(StrEnum):
    MANUAL = "MANUAL"
    STRUCTURED = "STRUCTURED"
    OCR = "OCR"
    PARSER = "PARSER"
    PHYSICAL_MEASUREMENT = "PHYSICAL_MEASUREMENT"
    IMAGE_SCALE = "IMAGE_SCALE"
    OTHER = "OTHER"


class ApplicabilityGrade(StrEnum):
    EXACT_CONFIGURATION = "EXACT_CONFIGURATION"
    SAME_GEOMETRY_CONFIRMED = "SAME_GEOMETRY_CONFIRMED"
    SAME_GENERATION_UNCONFIRMED_VARIANT = "SAME_GENERATION_UNCONFIRMED_VARIANT"
    ADJACENT_MARKET_UNCONFIRMED = "ADJACENT_MARKET_UNCONFIRMED"
    UNKNOWN_APPLICABILITY = "UNKNOWN_APPLICABILITY"


class EvidenceRole(StrEnum):
    PRIMARY = "PRIMARY"
    SUPPORTING = "SUPPORTING"
    CONFLICTING = "CONFLICTING"
    IDENTITY = "IDENTITY"
    OTHER = "OTHER"


class AxleRole(StrEnum):
    FRONT = "FRONT"
    REAR = "REAR"
    INTERMEDIATE = "INTERMEDIATE"
    OTHER = "OTHER"


class SteeringRole(StrEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    LINKED = "LINKED"


class LinkageType(StrEnum):
    FIXED_RATIO = "FIXED_RATIO"
    VARIABLE_RATIO = "VARIABLE_RATIO"
    FUNCTION = "FUNCTION"
    MODE_DEPENDENT = "MODE_DEPENDENT"
    UNKNOWN = "UNKNOWN"


class PhaseBehavior(StrEnum):
    OPPOSITE_PHASE = "OPPOSITE_PHASE"
    SAME_PHASE = "SAME_PHASE"
    MODE_OR_SPEED_DEPENDENT = "MODE_OR_SPEED_DEPENDENT"
    UNKNOWN = "UNKNOWN"


class MassBasis(StrEnum):
    UNLADEN = "UNLADEN"
    KERB = "KERB"
    OEM_LADEN = "OEM_LADEN"
    DESIGN_LOAD = "DESIGN_LOAD"
    GVW = "GVW"
    OTHER = "OTHER"


class WidthEnvelopeDefinition(StrEnum):
    BODY_EXCLUDING_MIRRORS = "BODY_EXCLUDING_MIRRORS"
    INCLUDING_MIRRORS_OPEN = "INCLUDING_MIRRORS_OPEN"
    INCLUDING_MIRRORS_FOLDED = "INCLUDING_MIRRORS_FOLDED"
    BODY_AND_FIXED_APPENDAGES = "BODY_AND_FIXED_APPENDAGES"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"
    OTHER = "OTHER"


class TrackDefinition(StrEnum):
    TYRE_CENTERLINE = "TYRE_CENTERLINE"
    WHEEL_CENTERLINE = "WHEEL_CENTERLINE"
    OUTER_TYRE_FACES = "OUTER_TYRE_FACES"
    INNER_TYRE_FACES = "INNER_TYRE_FACES"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"
    OTHER = "OTHER"


class TurningRadiusOrDiameter(StrEnum):
    RADIUS = "RADIUS"
    DIAMETER = "DIAMETER"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"


class TurningReference(StrEnum):
    CURB_TO_CURB = "CURB_TO_CURB"
    WALL_TO_WALL = "WALL_TO_WALL"
    WHEEL_PATH_OTHER = "WHEEL_PATH_OTHER"
    BODY_PATH_OTHER = "BODY_PATH_OTHER"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"


class TurningAxleScope(StrEnum):
    ALL_AXLES = "ALL_AXLES"
    ACTIVE_AXLES = "ACTIVE_AXLES"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"
    OTHER = "OTHER"


class WallEnvelopeScope(StrEnum):
    BODY_ONLY = "BODY_ONLY"
    BODY_AND_LOADS = "BODY_AND_LOADS"
    OEM_UNSPECIFIED = "OEM_UNSPECIFIED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ClearanceType(StrEnum):
    OEM_MINIMUM_UNSPECIFIED = "OEM_MINIMUM_UNSPECIFIED"
    RUNNING_CLEARANCE = "RUNNING_CLEARANCE"
    BETWEEN_AXLES = "BETWEEN_AXLES"
    FRONT_AXLE = "FRONT_AXLE"
    REAR_AXLE = "REAR_AXLE"
    DIFFERENTIAL = "DIFFERENTIAL"
    BATTERY_PACK = "BATTERY_PACK"
    COMPONENT_SPECIFIC = "COMPONENT_SPECIFIC"
    OTHER = "OTHER"


class GeometryRole(StrEnum):
    PLAN_BODY_ENVELOPE = "PLAN_BODY_ENVELOPE"
    AVT_PLAN_PROFILE = "AVT_PLAN_PROFILE"
    SIDE_SILHOUETTE = "SIDE_SILHOUETTE"
    LONGITUDINAL_LOWER_ENVELOPE = "LONGITUDINAL_LOWER_ENVELOPE"
    UNDERBODY_LOW_POINTS = "UNDERBODY_LOW_POINTS"
    TIRE_CIRCLE = "TIRE_CIRCLE"
    AXLE_DATUM_GEOMETRY = "AXLE_DATUM_GEOMETRY"
    OTHER = "OTHER"


class RepresentationType(StrEnum):
    POINT_SET = "POINT_SET"
    POLYLINE = "POLYLINE"
    POLYGON = "POLYGON"
    PARAMETRIC = "PARAMETRIC"
    FILE_REFERENCE = "FILE_REFERENCE"


class GeometryMethod(StrEnum):
    OEM_CAD = "OEM_CAD"
    OEM_DIMENSION_DRAWING = "OEM_DIMENSION_DRAWING"
    SCALED_DRAWING = "SCALED_DRAWING"
    PHYSICAL_SURVEY = "PHYSICAL_SURVEY"
    DERIVED = "DERIVED"
    OTHER = "OTHER"


class GeometryFidelity(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class ReadinessType(StrEnum):
    IDENTITY_RESOLVED = "IDENTITY_RESOLVED"
    DIMENSION_READY = "DIMENSION_READY"
    SWEPT_PATH_PARTIAL = "SWEPT_PATH_PARTIAL"
    AVT_READY = "AVT_READY"
    RAMP_SCREENING_READY = "RAMP_SCREENING_READY"
    VERTICAL_CLEARANCE_READY = "VERTICAL_CLEARANCE_READY"
    CLIENT_REFERENCE_READY = "CLIENT_REFERENCE_READY"


class ReadinessStatus(StrEnum):
    READY = "READY"
    NOT_READY = "NOT_READY"
    INDETERMINATE = "INDETERMINATE"


class AVTMappingStatus(StrEnum):
    READY = "READY"
    PARTIAL = "PARTIAL"
    BLOCKED = "BLOCKED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class DecisionState(StrEnum):
    SELECTED = "SELECTED"
    UNRESOLVED = "UNRESOLVED"
    REJECTED = "REJECTED"


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class QAFindingStatus(StrEnum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    RESOLVED = "RESOLVED"
